[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inference_server = { path = "../"}
actix-rt = "2.9.0"
actix-web = "4.4.0"
anyhow = "1.0.75"
